@startuml s'authentifier
title s'authentifier
hide footbox
actor client as "Utilisateur" order 1
participant app as ":App" order 2
database bdd as "Base de donnée" order 5

client ->> app: accèder à la page
activate app
create login as ":Login" order 3
app -> login : <<create>>
client <<-- app
deactivate app

client ->> app: click sur bouton \n "se connecter"
activate app
note left: L'utilisateur saisit\nses infos de connection
app -> login: connect(username, password)
activate login

login -> login: check(username, password)
activate login
login <<-- login
deactivate login

alt syntaxCorrect == true
    login -> bdd: executeQuery()
    activate bdd
    login <<-- bdd
    deactivate bdd
    
    alt userExist == true 
        create user as "currentUser:User" order 4
        login -> user : <<create>>
        app <<-- login
        client <<-- app
        deactivate app
    else else
        client <<-- login : erreur identification incorrect

    end
else else
    client <<-- login : erreur syntax incorrect
    deactivate login
end





@enduml