@startuml consulter une demande
title consulter une demande
hide footbox

actor client as "Utilisateur" order 1 
participant app as ":App" order 2 
database bdd as "Base de donnée"  order 6

client ->> app :accèder à la page
activate app
create tlc as ":TicketListControler" order 3
app -> tlc : <<create>>

app -> tlc : retrieveTicket(id) 
activate tlc
tlc -> bdd : executeQuery(id)
note over bdd: On récupère l'ensemble\ndes tickets et les données\nde l'utilisateur ayant créé \nle ticket
activate bdd
tlc <<-- bdd
deactivate bdd

create user as ":User" order 4
tlc -> user : <<create>>
tlc -> user : createTicket()
activate user   

create ticket as ":Ticket" order 5
user -> ticket : <<create>>
note right: créer un objet ticket\ncorrespondant à sa \ncatégorie 
tlc <<-- user:
deactivate user

app <<-- tlc
deactivate tlc

app -> tlc : displayTicket(id)
activate tlc

tlc -> ticket : display()
activate ticket

tlc <<-- ticket: 
deactivate ticket

app <<-- tlc
deactivate tlc
client <<-- app
deactivate app


@enduml