@startuml consulter l'ensemble des demandes
title consulter l'ensemble des demandes

actor client as "Utilisateur" order 1 
participant app as ":App" order 2 
database bdd as "Base de donnée"  order 6
hide footbox
client ->> app :accède à la page 
activate app
create tlc as ":TicketListControler" order 3
app -> tlc : <<create>>

app -> tlc : searchTickets() 
activate tlc
tlc -> bdd : executeQuery()
activate bdd
tlc <<-- bdd
deactivate bdd

loop as long as there's results
    create user as ":User" order 4
    tlc -> user : <<create>>
    tlc -> user : createTicket()
    activate user
    create ticket as ":Ticket" order 5
    user -> ticket : <<create>>
    tlc <<-- user :
    deactivate user
end
app <<-- tlc
deactivate tlc

app -> tlc : displayTickets()
activate tlc

loop i = tickets
tlc -> ticket : displayThumbnail()
activate ticket
tlc <<-- ticket: 
deactivate ticket
end


app <<-- tlc
deactivate tlc

opt search with filters
    app -> tlc: clearTickets()
    activate tlc
    loop i=tickets
        tlc -> ticket: <<destroy>>
        destroy ticket
    end
    app <<-- tlc
    deactivate tlc

    app -> tlc : searchTickets(filters) 
    activate tlc
    tlc -> bdd : executeQuery(filters)
    activate bdd
    tlc <<-- bdd
    deactivate bdd

    loop as long as there's results
        create user as ":User" order 4
        tlc -> user : <<create>>
        tlc -> user : createTicket()
        activate user
        create ticket as ":Ticket" order 5
        user -> ticket : <<create>>
        tlc <<-- user :
        deactivate user
    end
    app <<-- tlc
    deactivate tlc

    app -> tlc : displayTickets()
    activate tlc
    loop i = tickets
        tlc -> ticket : displayThumbnail()
        activate ticket
        tlc <<-- ticket: 
        deactivate ticket
    end
    
    app <-- tlc
    deactivate tlc
end
client <<-- app
deactivate app

@enduml