@startuml créer une demande
title Créer une demande\n""__Pré-requis__: Le demandeur s'est authentifié ""\n""et à appuyer sur le bouton 'création de demande'""

actor client as "Demandeur" order 1
participant app as ":App"   order 2
participant user as "currentUser:User" order 3
database bdd as "dataBase:" order 6
hide footbox

note over client : le demandeur\nsaisi le informations\nrelatif au ticket
client -> app: click sur bouton valider
activate app

app -> app : checkField
activate app
app <<-- app
deactivate app
alt all field complete == true
    app -> user: createTicket()
    activate user
    create ticket as ":Ticket" order 4
    user ->> ticket: <<create>>
    create conv as ":Conversation" order 5 
    activate ticket
    ticket ->> conv : <<create>>
    deactivate ticket
    app <<--user : Ticket
    deactivate user

    app -> ticket: save()
    activate ticket
    ticket -> bdd : executeQuery
    activate bdd
    ticket <<-- bdd
    deactivate bdd
    app <<-- ticket
    deactivate ticket
    client <<-- app: redirige sur la page qui affiche la demande
else else
    client <<-- app: error field uncompleted
    deactivate app
end


@enduml