@startuml editer une demande
title Editer une demande\n""__Pré-requis__: Le demandeur s'est connecté et consulte une demande qu'il a émit""

actor client as "Demandeur" order 1
participant app as ":App"   order 2
participant user as "currentUser:User" order 3
participant tlc as ":TicketListControler" order 4
participant ticket as ":Ticket" order 5
database bdd as "Base de donnée" order 6

app -> user: checkRights()
activate user
user -> tlc: getTicket(id)
activate tlc
user <<-- tlc
deactivate tlc

user -> ticket: getRequester()
activate ticket
user <<-- ticket : getRequester(): requester
deactivate ticket

opt requester == currentUser
    app <<-- user: afficher bouton de suppression
    deactivate user


    client ->> app: clic sur bouton éditer
    activate app
    client <<-- app: affiche la page edition
    deactivate app

    note over client: Le demandeur modifie \nles champs
    client ->> app: clic sur le bouton valider
    activate app

    app -> app : checkField
    activate app
    app <<-- app
    deactivate app
    alt all field complete == true
        app -> user: editTicket(t)
        activate user
        user -> ticket: edit()
        activate ticket
        user <<--ticket
        deactivate ticket

        user -> ticket: save()
        activate ticket
        ticket -> bdd: executeQuery()
        activate bdd
        ticket <<-- bdd
        deactivate bdd
        user <<-- ticket
        deactivate ticket
        app <<--user
        deactivate user

        client <<-- app: redirige sur la page qui affiche la demande
    else else
        client <<-- app: error field uncompleted
        deactivate app
    end

end
@enduml