@startuml editer une demande
title Editer une demande\n""__Pré-requis__: L'utilisateur s'est connecté""

actor client as "User" order 1
participant app as ":App"   order 2
participant ticketClass as ":Ticket" order 3
database bdd as "dataBase:" order 4

client ->> app: HttpRequest()
note left : Click on \na ticket 
app ->> client: displayEditTicket()


alt pas d'erreur

    client ->> app: HttpRequest()
    note left: Edit ticket\ninformation
    activate app
    app -> ticketClass: saveTicket()
    activate ticketClass
    ticketClass -> bdd: executeQuery()
    activate bdd
    bdd -->> ticketClass: executeQuery():
    deactivate bdd
    ticketClass -->> app: saveTicket():
    deactivate ticketClass
    app ->> client: HttpRequest():
    deactivate app

else else

    client ->> app: HttpRequest()
    note left: Edit ticket\ninformation
    activate app
    app ->> client: HttpRequest(): erreur
    deactivate app
    
end

@enduml