@startuml supprimer un ticket
title Supprimer une demande\n""__Pré-requis__: Le demandeur s'est connecté""\n"" et consulte une demande""
actor client as "Demander" order 1
participant app as ":App"   order 2
participant user as "currentUser:User" order 3
participant tlc as ":TicketListControler" order 4
participant ticket as "t:Ticket" order 5
database bdd as "Base de donnée" order 6

app -> user: checkRights(id)
activate user
user -> tlc: getTicket(id)
activate tlc
user <<-- tlc
deactivate tlc

user -> ticket: getRequester()
activate ticket
user <<-- ticket : getRequester(): requester
deactivate ticket

opt requester == currentUser
    app <<-- user: afficher bouton de suppression
    deactivate user

    client -> app: clic sur bouton de suppression
    activate app
    app -> user: deleteTicket(id)
    activate user
    user -> tlc: getTicket(id)
    activate tlc
    user <<-- tlc
    deactivate tlc

    user -> ticket: delete()
    activate ticket
    ticket -> bdd: executeQuerry
    activate bdd
    ticket <<-- bdd
    deactivate bdd
    user <<-- ticket
    deactivate ticket

    app <<-- user
    deactivate user

    client <<-- app
    deactivate app
end
app <<-- user
deactivate user
@enduml