@startuml
title Navigation

state S1 as "l'utilisateur n'est pas connecter"
state S2 as "l'utilisateur est connecté" 

[*] --> S1
S1  --> S2 : s'authentifier
S2  --> S1 : deconnecter
S1  --> [*]
S2  --> [*]
@enduml