@startuml
title L'utilisateur est connecté


  state S5 as "consultation de l'ensemble\n des demandes"
  state S6 as "consultation d'une demande"
  state S7 as "création d'une demande"
  state S8 as "édition d'une demande"
  state S9 as "supretion d'une demande"
  state S10 as "réponse a une demande"

  [*] -> S5
  S5 --> S6 : when (clic sur une demande)/ displayTicket(id)
  S6 --> S5 : when (clic sur "fermer" ou precedent)/ displayTickets()
  S5 --> S7 : when (clic sur "création de demande")/createTicket()
  S6 --> S8 : when (clic sur "édité une demande")[currentUser = requesteur]/edit()
  S6 --> S9 : when (clic sur une "supprimer")[currentUser = requesteur]/delete()
  S6 --> S10 : when (clic sur une le "prendre en charge")[currentUser = requesteur or currentUser = helper]/handleTicket(id)
  S9 --> S5:  /displayTickets()
  S7 --> S6 : when (clic sur "valider")/save()
  S8 --> S6 : when (clic sur "valider")/save()
  S10 --> S6 : when (clic sur "valider")/save()
@enduml