@startuml
left to right direction
actor Utilisateur as "Utilisateur" <<primary>>
actor Aidant
actor Demandeur
agent Serveur as "Serveur" <<secondary>>

Utilisateur <|-- Aidant
Utilisateur <|-- Demandeur

rectangle "CoHub" {
    usecase UC1 as "Consulter \n l'ensemble \n des demandes"
    usecase UC2 as "Consulter \n une demande"
    usecase UC3 as "Filtrer"
    usecase UC5 as "Créer une demande"
    usecase UC6 as "Editer une demande"
    usecase UC7 as "Répondre à \n une demande"
    usecase UC8 as "S'authentifier"
    usecase UC9 as "Supprimer une demande"
    usecase UC10 as "Supprimer les demandes \n de plus 30jours " 

    Utilisateur -- (UC1)
    UC1 <.. UC2 : <<extend>>
    UC1 <.. UC3 : <<extend>>
    

    Demandeur -- UC5
    Demandeur -- UC9
    Demandeur -- UC6



    Aidant -- UC7
    UC7 ..> UC8 : <<include>>
    UC5 ..> UC8 : <<include>>
    UC6 ..> UC8 : <<include>>
    UC9 ..> UC8 : <<include>>

    UC10 --- Serveur
}
@enduml