@startuml consulter un ticket

actor client as "User" order 1 
participant server as "Server"   order 2
database bdd as "dataBase:" <<static>> order 4

client ->> server : HttpRequest()
activate server
note left : Click on\na ticket
create ticketCtrl as ":TicketControler" order 3
server -> ticketCtrl : <<create>>

server -> ticketCtrl : getTicket()
activate ticketCtrl

ticketCtrl -> bdd : executeQuery()
activate bdd
bdd -->> ticketCtrl
deactivate bdd

ticketCtrl -->> server
deactivate ticketCtrl
destroy ticketCtrl

server ->> client : displayTicket()
deactivate server





@enduml