@startuml consulter un ticket
title consulter un ticket

actor client as "Utilisateur" order 1 
participant app as "App" order 2 
participant tlc as ":TicketListControler" order 3
participant ticket as ":Ticket" order 4

client ->> app: click on ticket
activate app
app -> tlc: displayTicket(ticket)
activate tlc
tlc -> ticket: display()
activate ticket
tlc <<-- ticket
deactivate ticket
app <<-- tlc
deactivate tlc
deactivate app






@enduml