@startuml consulter l'ensemble des tickets
title consulter l'ensemble des tickets

actor client as "Utilisateur" order 1 
participant app as "App" order 2 
participant tlc as ":TicketListControler" order 3
database bdd as "database:"  order 5

client -> app :accède à la page 
app -> tlc : searchTickets() 
activate tlc
tlc -> bdd : executeQuery()
activate bdd
tlc <<-- bdd
deactivate bdd

loop as long as there's results
    create ticket as ":Ticket" order 4
    tlc -> ticket : <<create>>
end
app <<-- tlc
deactivate tlc

app -> tlc : displayTickets()
activate tlc

loop i = tickets
tlc -> ticket : display()
activate ticket
tlc <<-- ticket: 
deactivate ticket
end

app <<-- tlc
deactivate tlc

opt search with filters
    app -> tlc : searchTickets(filters) 
    activate tlc
    tlc -> bdd : executeQuery(filters)
    activate bdd
    tlc <<-- bdd
    deactivate bdd

    loop as long as there's results
        opt ticket not already create
            create ticket as ":Ticket" order 41
            tlc -> ticket : <<create>>
        end
        
        
    end
    app <<-- tlc
    deactivate tlc

    app -> tlc : displayTickets()
    activate tlc
    loop i = tickets
    tlc -> ticket : display()
    activate ticket
    tlc <<-- ticket: ticket(): string
    deactivate ticket
    end
    app <-- tlc : displayTickets()
    deactivate tlc
end


@enduml